[Variables]
ThemeName=Glass
SizeName=Small
Scale=0.75

LayoutName=LyricsOnly
Layout=#LayoutName#

Shape=Rounded
CornerR=18
BtnR=10
ApplyR=12

ShowNowPlaying=0
ShowLyrics=1
ShowDebug=1
IsGlass=1

FontMain=Yu Gothic UI Semibold
FontSub=Yu Gothic UI

LyricOffsetMs=0

BgFill=20,20,30,110
Border=160,230,255,120
Glow=160,230,255,16
TextMain=235,245,255,255
TextGlow=160,230,255,60
TextFaded=200,220,240,85
